/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package motorphgui;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author admin
 */
public class Employee_DetailsResult extends javax.swing.JDialog {


    public Employee_DetailsResult(java.awt.Frame parent, boolean modal, String[] data) {
        super(parent, modal);
        initComponents();

        if (data != null && data.length >= 19) {
            lbl_resID.setText(data[0]);
            lbl_resName.setText(data[1] + ", " + data[2]);
            lbl_resBday.setText(data[3]);
            lbl_resAdd.setText("<html>" + data[4] + "</html>");
            lbl_resPhone.setText(data[5]);
            lbl_resSSS.setText(data[6]);
            lbl_resPIN.setText(data[7]);
            lbl_resTIN.setText(data[8]);
            lbl_resMID.setText(data[9]);
            lbl_resES.setText(data[10]);
            lbl_resPOS.setText(data[11]);
            lbl_resIS.setText(data[12]);
            
            
            lbl_resBasicSal.setText(formatCurrency(data[13]));
            lbl_resRiceSub.setText(formatCurrency(data[14]));
            lbl_resPhoneAllowance.setText(formatCurrency(data[15]));
            lbl_resClothing.setText(formatCurrency(data[16]));
            lbl_resSemiMonthly.setText(formatCurrency(data[17]));
            lbl_resHourly.setText(formatCurrency(data[18]));

            double rice = parseAmount(data[14]);
            double phone = parseAmount(data[15]);
            double clothing = parseAmount(data[16]);
            double proratedTotal = rice + phone + clothing;
            lbl_resProratedAll.setText(formatCurrency(String.valueOf(proratedTotal)));

        } else {
            JOptionPane.showMessageDialog(this, "⚠️ Invalid employee data received.");
        }
    }

    private double parseAmount(String raw) {
    try {
        return Double.parseDouble(raw);
    } catch (NumberFormatException e) {
        return 0.0;
    }
}
    
    private String formatCurrency(String raw) {
        try {
            double value = Double.parseDouble(raw);
            return String.format("₱%,.2f", value);
        } catch (NumberFormatException e) {
            return raw;
        }
    }

    public Employee_DetailsResult(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_main = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_resID = new javax.swing.JLabel();
        lbl_resName = new javax.swing.JLabel();
        lbl_resBday = new javax.swing.JLabel();
        lbl_resAdd = new javax.swing.JLabel();
        lbl_resPhone = new javax.swing.JLabel();
        lbl_resSSS = new javax.swing.JLabel();
        lbl_resPIN = new javax.swing.JLabel();
        lbl_resTIN = new javax.swing.JLabel();
        lbl_resMID = new javax.swing.JLabel();
        lbl_resES = new javax.swing.JLabel();
        lbl_resPOS = new javax.swing.JLabel();
        lbl_resIS = new javax.swing.JLabel();
        lbl_resBasicSal = new javax.swing.JLabel();
        lbl_resRiceSub = new javax.swing.JLabel();
        lbl_resPhoneAllowance = new javax.swing.JLabel();
        lbl_resClothing = new javax.swing.JLabel();
        lbl_resSemiMonthly = new javax.swing.JLabel();
        lbl_resHourly = new javax.swing.JLabel();
        lbl_resProratedAll = new javax.swing.JLabel();
        btn_Results_Home = new javax.swing.JButton();
        btn_Results_Home1 = new javax.swing.JButton();
        btn_Results_UpdateRec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_main.setBackground(new java.awt.Color(204, 255, 255));
        lbl_main.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        lbl_main.setText("Employee Details");

        jLabel1.setText("Employee ID:");

        jLabel2.setText("Name:");

        jLabel3.setText("Birthday:");

        jLabel4.setText("Address:");

        jLabel5.setText("SSN:");

        jLabel6.setText("Phone Number:");

        jLabel7.setText("PhilHealth Number:");

        jLabel8.setText("TIN:");

        jLabel9.setText("Pag-Ibig Number:");

        jLabel10.setText("Employment Status:");

        jLabel11.setText("Position:");

        jLabel12.setText("Immediate Supervisor:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Basic Salary:");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel14.setText("Rice Subsidy:");

        jLabel15.setText("Phone Allowance:");

        jLabel16.setText("Clothing Allowance:");

        jLabel17.setText("Gross Semi-Monthly Rate:");

        jLabel18.setText("Hourly Rate:");

        jLabel19.setText("Pro-rated Total Allowance:");

        lbl_resID.setText("EMP_ID_RESULT");

        lbl_resName.setText("EMP_NAME_RESULT");

        lbl_resBday.setText("EMP_BDAY_RESULT");

        lbl_resAdd.setText("EMP_ADDRESS_RESULT");
        lbl_resAdd.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_resPhone.setText("EMP_PHONE_RESULT");

        lbl_resSSS.setText("EMP_SSS_RESULT");

        lbl_resPIN.setText("EMP_PIN_RESULT");

        lbl_resTIN.setText("EMP_TIN_RESULT");

        lbl_resMID.setText("EMP_MID_RESULT");

        lbl_resES.setText("EMP_ES_RESULT");

        lbl_resPOS.setText("EMP_POS_RESULT");

        lbl_resIS.setText("EMP_IS_RESULT");

        lbl_resBasicSal.setText("EMP_Basic_RESULT");

        lbl_resRiceSub.setText("EMP_RiceSub_RESULT");

        lbl_resPhoneAllowance.setText("EMP_PhoneAllowance_RESULT");

        lbl_resClothing.setText("EMP_Clothing_RESULT");

        lbl_resSemiMonthly.setText("EMP_GSMR_RESULT");

        lbl_resHourly.setText("EMP_HRate_RESULT");

        lbl_resProratedAll.setText("EMP_PTA_RESULT");

        btn_Results_Home.setText("Back to Main");
        btn_Results_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Results_HomeActionPerformed(evt);
            }
        });

        btn_Results_Home1.setText("Exit");
        btn_Results_Home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Results_Home1ActionPerformed(evt);
            }
        });

        btn_Results_UpdateRec.setForeground(new java.awt.Color(51, 102, 0));
        btn_Results_UpdateRec.setText("Update Record");
        btn_Results_UpdateRec.setToolTipText("");
        btn_Results_UpdateRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Results_UpdateRecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(btn_Results_Home)
                .addGap(31, 31, 31)
                .addComponent(btn_Results_UpdateRec)
                .addGap(43, 43, 43)
                .addComponent(btn_Results_Home1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_main)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_resMID, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_resTIN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(lbl_resPIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_resBday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_resName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(lbl_resID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_resAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_resPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lbl_resPOS, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_resIS, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_resES, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(lbl_resSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbl_resHourly, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl_resSemiMonthly, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl_resClothing, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl_resPhoneAllowance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl_resRiceSub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl_resBasicSal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_resProratedAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_main)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_resID)
                    .addComponent(lbl_resBasicSal)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14)
                    .addComponent(lbl_resName)
                    .addComponent(lbl_resRiceSub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel15)
                    .addComponent(lbl_resBday)
                    .addComponent(lbl_resPhoneAllowance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_resClothing))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(lbl_resSemiMonthly)))
                    .addComponent(lbl_resAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lbl_resHourly)
                    .addComponent(jLabel6)
                    .addComponent(lbl_resPhone))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_resProratedAll))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbl_resSSS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_resPIN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lbl_resTIN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lbl_resMID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lbl_resES))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lbl_resPOS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(lbl_resIS))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Results_UpdateRec)
                        .addComponent(btn_Results_Home1))
                    .addComponent(btn_Results_Home))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Results_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Results_HomeActionPerformed
        this.dispose();
        MainDialog mainDialog = new MainDialog(new javax.swing.JFrame(), true);
        mainDialog.setVisible(true);
    }//GEN-LAST:event_btn_Results_HomeActionPerformed

    private void btn_Results_Home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Results_Home1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Results_Home1ActionPerformed

    private void btn_Results_UpdateRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Results_UpdateRecActionPerformed
        this.dispose();
        Employee_DetailsUpdate updateDialog = new Employee_DetailsUpdate(null, true);
        updateDialog.setVisible(true);
    }//GEN-LAST:event_btn_Results_UpdateRecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            // Dummy data just for manual testing
            String[] dummy = {
                "10001", "Juan Dela Cruz", "1990-01-01", "Makati City", "09171234567",
                "SSS1234567", "PIN1234567", "TIN1234567", "MID1234567", "Regular",
                "Software Engineer", "Jane Smith", "50000", "1500", "1000", "1000",
                "25000", "300", "3500"
            };
            Employee_DetailsResult dialog = new Employee_DetailsResult(new JFrame(), true, dummy);
            dialog.setLocationRelativeTo(null); 
            dialog.setVisible(true);
        });
    

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Results_Home;
    private javax.swing.JButton btn_Results_Home1;
    private javax.swing.JButton btn_Results_UpdateRec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_main;
    private javax.swing.JLabel lbl_resAdd;
    private javax.swing.JLabel lbl_resBasicSal;
    private javax.swing.JLabel lbl_resBday;
    private javax.swing.JLabel lbl_resClothing;
    private javax.swing.JLabel lbl_resES;
    private javax.swing.JLabel lbl_resHourly;
    private javax.swing.JLabel lbl_resID;
    private javax.swing.JLabel lbl_resIS;
    private javax.swing.JLabel lbl_resMID;
    private javax.swing.JLabel lbl_resName;
    private javax.swing.JLabel lbl_resPIN;
    private javax.swing.JLabel lbl_resPOS;
    private javax.swing.JLabel lbl_resPhone;
    private javax.swing.JLabel lbl_resPhoneAllowance;
    private javax.swing.JLabel lbl_resProratedAll;
    private javax.swing.JLabel lbl_resRiceSub;
    private javax.swing.JLabel lbl_resSSS;
    private javax.swing.JLabel lbl_resSemiMonthly;
    private javax.swing.JLabel lbl_resTIN;
    // End of variables declaration//GEN-END:variables
}
