/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package motorphgui;

import javax.swing.*;
import java.io.*;
import java.util.*;

/**
 *
 * @author admin
 */
public class Employee_DetailsUpdate extends javax.swing.JDialog {

    private List<String[]> employeeDataList = new ArrayList<>();

    public Employee_DetailsUpdate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txt_Update_Address.setLineWrap(true);
        txt_Update_Address.setWrapStyleWord(true);
        loadEmployeeData();
        setupComboBoxListener();
    }

private void loadEmployeeData() {
    combobox_EmpID.addItem("Add New Employee");
    List<String[]> data = CSVUtil.readCSV("src/main/resources/employee-data.csv");

    if (data != null) {
        for (String[] row : data) {
            if (row.length >= 19) {
                employeeDataList.add(row);
                combobox_EmpID.addItem(row[0]);
            }
        }
    }
}


    private void setupComboBoxListener() {
        combobox_EmpID.addActionListener(e -> {
            String selectedId = (String) combobox_EmpID.getSelectedItem();
            if (selectedId == null || selectedId.equals("Add New Employee")) {
                clearTextFields();
                return;
            }

            for (String[] emp : employeeDataList) {
                if (emp[0].equals(selectedId)) {
                    txt_Update_Name.setText(emp[1] + ", " + emp[2]);
                    txt_Update_Bday.setText(emp[3]);
                    txt_Update_Address.setText(emp[4]);
                    txt_Update_Phone.setText(emp[5]);
                    txt_Update_SSN.setText(emp[6]);
                    txt_Update_MID.setText(emp[7]);
                    txt_Update_TIN.setText(emp[8]);
                    txt_Update_PIN.setText(emp[9]);
                    txt_Update_EmpStat.setText(emp[10]);
                    txt_Update_Position.setText(emp[11]);
                    txt_Update_ImmediateSup.setText(emp[12]);
                    txt_Update_Basic.setText(emp[13]);
                    txt_Update_RiceSub.setText(emp[14]);
                    txt_Update_PhoneAll.setText(emp[15]);
                    txt_Update_ClothingAll.setText(emp[16]);
                    txt_Update_Semi.setText(emp[17]);
                    txt_Update_Hourly.setText(emp[18]);
                    break;
                }
            }
        });
    }

    private void clearTextFields() {
        txt_Update_Name.setText("");
        txt_Update_Bday.setText("");
        txt_Update_Address.setText("");
        txt_Update_Phone.setText("");
        txt_Update_SSN.setText("");
        txt_Update_MID.setText("");
        txt_Update_TIN.setText("");
        txt_Update_PIN.setText("");
        txt_Update_EmpStat.setText("");
        txt_Update_Position.setText("");
        txt_Update_ImmediateSup.setText("");
        txt_Update_Basic.setText("");
        txt_Update_RiceSub.setText("");
        txt_Update_PhoneAll.setText("");
        txt_Update_ClothingAll.setText("");
        txt_Update_Semi.setText("");
        txt_Update_Hourly.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_main = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btn_Update_Back = new javax.swing.JButton();
        btn_Update_Exit = new javax.swing.JButton();
        btn_Update_AddUpdate = new javax.swing.JButton();
        txt_Update_Name = new javax.swing.JTextField();
        txt_Update_Bday = new javax.swing.JTextField();
        txt_Update_Phone = new javax.swing.JTextField();
        txt_Update_SSN = new javax.swing.JTextField();
        txt_Update_PIN = new javax.swing.JTextField();
        txt_Update_TIN = new javax.swing.JTextField();
        txt_Update_MID = new javax.swing.JTextField();
        txt_Update_EmpStat = new javax.swing.JTextField();
        txt_Update_Position = new javax.swing.JTextField();
        txt_Update_ImmediateSup = new javax.swing.JTextField();
        txt_Update_Basic = new javax.swing.JTextField();
        txt_Update_RiceSub = new javax.swing.JTextField();
        txt_Update_PhoneAll = new javax.swing.JTextField();
        txt_Update_ClothingAll = new javax.swing.JTextField();
        txt_Update_Semi = new javax.swing.JTextField();
        txt_Update_Hourly = new javax.swing.JTextField();
        btn_Update_Delete = new javax.swing.JButton();
        combobox_EmpID = new javax.swing.JComboBox<>();
        jLabel222 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Update_Address = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_main.setBackground(new java.awt.Color(204, 255, 255));
        lbl_main.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        lbl_main.setText("Employee Details");

        jLabel1.setText("Employee ID:");

        jLabel2.setText("Name:");

        jLabel3.setText("Birthday:");

        jLabel4.setText("Address:");

        jLabel5.setText("SSN:");

        jLabel6.setText("Phone Number:");

        jLabel7.setText("PhilHealth Number:");

        jLabel8.setText("TIN:");

        jLabel9.setText("Pag-Ibig Number:");

        jLabel10.setText("Employment Status:");

        jLabel11.setText("Position:");

        jLabel12.setText("Immediate Supervisor:");

        jLabel13.setText("Basic Salary:");

        jLabel14.setText("Rice Subsidy:");

        jLabel15.setText("Phone Allowance:");

        jLabel16.setText("Clothing Allowance:");

        jLabel17.setText("Gross Semi-Monthly Rate:");

        jLabel18.setText("Hourly Rate:");

        btn_Update_Back.setText("Back to Main");
        btn_Update_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Update_BackActionPerformed(evt);
            }
        });

        btn_Update_Exit.setText("Exit");
        btn_Update_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Update_ExitActionPerformed(evt);
            }
        });

        btn_Update_AddUpdate.setForeground(new java.awt.Color(51, 102, 0));
        btn_Update_AddUpdate.setText("Add/Update Record");
        btn_Update_AddUpdate.setToolTipText("");
        btn_Update_AddUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Update_AddUpdateActionPerformed(evt);
            }
        });

        btn_Update_Delete.setForeground(new java.awt.Color(153, 0, 51));
        btn_Update_Delete.setText("Delete Record");
        btn_Update_Delete.setToolTipText("");
        btn_Update_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Update_DeleteActionPerformed(evt);
            }
        });

        jLabel222.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        jLabel222.setText("(Last Name, First Name)");

        txt_Update_Address.setColumns(20);
        txt_Update_Address.setRows(5);
        jScrollPane1.setViewportView(txt_Update_Address);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(lbl_main))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(combobox_EmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(txt_Update_Basic, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel222)
                        .addGap(6, 6, 6)
                        .addComponent(txt_Update_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(txt_Update_RiceSub, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(txt_Update_Bday, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(txt_Update_PhoneAll, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Update_ClothingAll, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Update_Semi, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Update_Hourly, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(txt_Update_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(txt_Update_SSN, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txt_Update_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(txt_Update_TIN, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(txt_Update_MID, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txt_Update_EmpStat, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(txt_Update_Position, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txt_Update_ImmediateSup, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btn_Update_Back)
                        .addGap(40, 40, 40)
                        .addComponent(btn_Update_AddUpdate)
                        .addGap(34, 34, 34)
                        .addComponent(btn_Update_Exit)
                        .addGap(128, 128, 128)
                        .addComponent(btn_Update_Delete)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbl_main)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combobox_EmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Update_Basic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel13))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel222))
                    .addComponent(txt_Update_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14))
                    .addComponent(txt_Update_RiceSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Update_Bday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Update_PhoneAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel15))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_Update_ClothingAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txt_Update_Semi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txt_Update_Hourly, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel17)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel18)))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(txt_Update_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_Update_SSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Update_PIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(txt_Update_TIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(txt_Update_MID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addComponent(txt_Update_EmpStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txt_Update_Position, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12))
                    .addComponent(txt_Update_ImmediateSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Update_Back)
                    .addComponent(btn_Update_AddUpdate)
                    .addComponent(btn_Update_Exit)
                    .addComponent(btn_Update_Delete))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Update_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Update_BackActionPerformed
        this.dispose(); 
        MainDialog MainDia = new MainDialog(null, true);    
        MainDia.setVisible(true);
    }//GEN-LAST:event_btn_Update_BackActionPerformed

    private void btn_Update_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Update_ExitActionPerformed
        System.exit(0);      // TODO add your handling code here:
    }//GEN-LAST:event_btn_Update_ExitActionPerformed

    private void btn_Update_AddUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Update_AddUpdateActionPerformed
        String empId = (String) combobox_EmpID.getSelectedItem();
        if (empId == null || empId.isEmpty()) return;

        String[] nameParts = txt_Update_Name.getText().split(",", 2);
        String lastName = nameParts.length > 0 ? nameParts[0].trim() : "";
        String firstName = nameParts.length > 1 ? nameParts[1].trim() : "";

        String[] newRecord = new String[]{
                empId.equals("Add New Employee") ? generateNewEmpId() : empId,
                lastName,
                firstName,
                txt_Update_Bday.getText(),
                txt_Update_Address.getText(),
                txt_Update_Phone.getText(),
                txt_Update_SSN.getText(),
                txt_Update_MID.getText(),
                txt_Update_TIN.getText(),
                txt_Update_PIN.getText(),
                txt_Update_EmpStat.getText(),
                txt_Update_Position.getText(),
                txt_Update_ImmediateSup.getText(),
                txt_Update_Basic.getText(),
                txt_Update_RiceSub.getText(),
                txt_Update_PhoneAll.getText(),
                txt_Update_ClothingAll.getText(),
                txt_Update_Semi.getText(),
                txt_Update_Hourly.getText()
        };

        boolean updated = false;
        for (int i = 0; i < employeeDataList.size(); i++) {
            if (employeeDataList.get(i)[0].equals(newRecord[0])) {
                String[] existing = employeeDataList.get(i);
                // Preserve columns T and U if they exist
                if (existing.length > 19) {
                    newRecord = Arrays.copyOf(newRecord, 21);
                    newRecord[19] = existing[19];
                    newRecord[20] = existing[20];
                }
                employeeDataList.set(i, newRecord);
                updated = true;
                break;
            }
        }

        if (!updated) {
            // New record: Add default columns T and U
            newRecord = Arrays.copyOf(newRecord, 21);
            newRecord[19] = "User12345"; // default column T
            newRecord[20] = "NO";        // default column U

            employeeDataList.add(newRecord);
            combobox_EmpID.addItem(newRecord[0]);
        }

        saveEmployeeDataToCSV();
        JOptionPane.showMessageDialog(this, updated ? "Record updated!" : "New employee added!");

    }//GEN-LAST:event_btn_Update_AddUpdateActionPerformed

    private void txt_Update_EmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Update_EmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Update_EmpIDActionPerformed

    private void btn_Update_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Update_DeleteActionPerformed
        String selectedId = (String) combobox_EmpID.getSelectedItem();
        if (selectedId == null || selectedId.equals("Add New Employee")) {
            JOptionPane.showMessageDialog(this, "Please select a valid employee to delete.");
            return;
        }

        employeeDataList.removeIf(emp -> emp[0].equals(selectedId));
        combobox_EmpID.removeItem(selectedId);
        saveEmployeeDataToCSV();
        clearTextFields();
        JOptionPane.showMessageDialog(this, "Record deleted.");
    }//GEN-LAST:event_btn_Update_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            Employee_DetailsUpdate dialog = new Employee_DetailsUpdate(new javax.swing.JFrame(), true);
            dialog.setLocationRelativeTo(null); 
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }


    private void saveEmployeeDataToCSV() {
    CSVUtil.writeCSV("src/main/resources/employee-data.csv", employeeDataList);
}


    private String generateNewEmpId() {
        int maxId = 0;
        for (String[] emp : employeeDataList) {
            try {
                int id = Integer.parseInt(emp[0].replaceAll("[^0-9]", ""));
                if (id > maxId) maxId = id;
            } catch (NumberFormatException ignored) {
            }
        }
        return String.valueOf(maxId + 1);
    }

    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Update_AddUpdate;
    private javax.swing.JButton btn_Update_Back;
    private javax.swing.JButton btn_Update_Delete;
    private javax.swing.JButton btn_Update_Exit;
    private javax.swing.JComboBox<String> combobox_EmpID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel222;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_main;
    private javax.swing.JTextArea txt_Update_Address;
    private javax.swing.JTextField txt_Update_Basic;
    private javax.swing.JTextField txt_Update_Bday;
    private javax.swing.JTextField txt_Update_ClothingAll;
    private javax.swing.JTextField txt_Update_EmpStat;
    private javax.swing.JTextField txt_Update_Hourly;
    private javax.swing.JTextField txt_Update_ImmediateSup;
    private javax.swing.JTextField txt_Update_MID;
    private javax.swing.JTextField txt_Update_Name;
    private javax.swing.JTextField txt_Update_PIN;
    private javax.swing.JTextField txt_Update_Phone;
    private javax.swing.JTextField txt_Update_PhoneAll;
    private javax.swing.JTextField txt_Update_Position;
    private javax.swing.JTextField txt_Update_RiceSub;
    private javax.swing.JTextField txt_Update_SSN;
    private javax.swing.JTextField txt_Update_Semi;
    private javax.swing.JTextField txt_Update_TIN;
    // End of variables declaration//GEN-END:variables
}
