/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorphgui;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;


/**
 *
 * @author admin
 */
public class ListOfEmployees extends javax.swing.JFrame {

    /**
     * Creates new form ListOfEmployees
     */
    public ListOfEmployees() {
        initComponents();
        loadEmployeeData();
        setupTableClickHandler();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_ListOfEmployees = new javax.swing.JTable();
        lbl_main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_ListOfEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Last Name", "First Name", "SSS Number", "PhilHealth Number", "TIN", "Pag-IBIG Number"
            }
        ));
        jScrollPane1.setViewportView(table_ListOfEmployees);

        lbl_main.setBackground(new java.awt.Color(204, 255, 255));
        lbl_main.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        lbl_main.setText("List of Employees");
        lbl_main.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addComponent(lbl_main)
                .addGap(336, 336, 336))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_main)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    private void loadEmployeeData() {
        String[] columnNames = {"Employee ID", "Last Name", "First Name", "SSS Number", "PhilHealth Number", "TIN", "Pag-IBIG Number"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        try {
            // Get the path to the resource CSV file
            String filePath = getClass().getResource("/employee-data.csv").getPath();

            List<String[]> rows = CSVUtil.readCSV(filePath);
            if (rows != null && !rows.isEmpty()) {
                for (int i = 1; i < rows.size(); i++) { // skip header
                    String[] data = rows.get(i);
                    if (data.length >= 10) {
                        String[] row = {
                            data[0].trim(), // Employee ID
                            data[1].trim(), // Last Name
                            data[2].trim(), // First Name
                            data[6].trim(), // SSS Number
                            data[7].trim(), // PhilHealth Number
                            data[8].trim(), // TIN
                            data[9].trim()  // Pag-IBIG Number
                        };
                        model.addRow(row);
                    }
                }
            }

            table_ListOfEmployees.setModel(model);
            table_ListOfEmployees.setDefaultEditor(Object.class, null); // Make non-editable

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading employee data: " + e.getMessage());
        }
    }

    private void setupTableClickHandler() {
        table_ListOfEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int selectedRow = table_ListOfEmployees.getSelectedRow();
                if (selectedRow >= 0) {
                    String employeeID = (String) table_ListOfEmployees.getValueAt(selectedRow, 0);
                    showEmployeeDetails(employeeID);
                }
            }
        });
    }    
    
    
    private void showEmployeeDetails(String employeeID) {
        try {
            String filePath = getClass().getResource("/employee-data.csv").getPath();
            List<String[]> rows = CSVUtil.readCSV(filePath);

            if (rows != null && rows.size() > 1) {
                for (int i = 1; i < rows.size(); i++) {
                    String[] data = rows.get(i);
                    if (data[0].trim().equals(employeeID)) {
                        // Pass data to Employee_DetailsResult
                        Employee_DetailsResult detailsWindow = new Employee_DetailsResult(this, true, data);
                        detailsWindow.setVisible(true);
                        break;
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading employee details: " + e.getMessage());
        }
    }
    
    public static void main(String args[]) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(ListOfEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new ListOfEmployees().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_main;
    private javax.swing.JTable table_ListOfEmployees;
    // End of variables declaration//GEN-END:variables
}
