/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package motorphgui;


import javax.swing.JFrame;


/**
 *
 * @author admin
 */
public class MainDialog_RF extends javax.swing.JDialog {
        private String firstName;
        private String lastName;
        private String empID;


        public MainDialog_RF(java.awt.Frame parent, boolean modal, String empID, String firstName, String lastName) {
            super(parent, modal);
            this.empID = empID;
            this.firstName = firstName;
            this.lastName = lastName;
            initComponents();
            lbl_User.setText(lastName + ", " + firstName);
        }
                /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        btn_MEDetails = new javax.swing.JButton();
        btn_MExit = new javax.swing.JButton();
        btn_MWHours = new javax.swing.JButton();
        btn_MPPayroll = new javax.swing.JButton();
        lbl_main = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_User = new javax.swing.JLabel();
        btn_attendance = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MotorPH Payroll System");

        btn_MEDetails.setText("Employee Details");
        btn_MEDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MEDetailsActionPerformed(evt);
            }
        });

        btn_MExit.setText("Exit");
        btn_MExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MExitActionPerformed(evt);
            }
        });

        btn_MWHours.setText("Work Hours");
        btn_MWHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MWHoursActionPerformed(evt);
            }
        });

        btn_MPPayroll.setText("Process Payroll");
        btn_MPPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MPPayrollActionPerformed(evt);
            }
        });

        lbl_main.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        lbl_main.setText("MotorPH Payroll System");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setText("Logged in as:");

        lbl_User.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lbl_User.setText("lbl_user");

        btn_attendance.setText("Attendance Viewer");
        btn_attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attendanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lbl_main))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_MWHours, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_MPPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_MExit, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbl_User, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8)))
                            .addComponent(btn_MEDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_attendance, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbl_main)
                .addGap(6, 6, 6)
                .addComponent(btn_MEDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_attendance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_MWHours)
                .addGap(6, 6, 6)
                .addComponent(btn_MPPayroll)
                .addGap(6, 6, 6)
                .addComponent(btn_MExit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_User))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MEDetailsActionPerformed(java.awt.event.ActionEvent evt) {                                              
//GEN-FIRST:event_btn_MEDetailsActionPerformed
        this.dispose(); 

        RF_Employee_DetailsResult detailsDialog = new RF_Employee_DetailsResult(
            (java.awt.Frame) this.getParent(),
            true,
            empID 
        );

        detailsDialog.setLocationRelativeTo(null);
        detailsDialog.setVisible(true);
    }//GEN-LAST:event_btn_MEDetailsActionPerformed

    private void btn_MExitActionPerformed(java.awt.event.ActionEvent evt) {                                          
//GEN-FIRST:event_btn_MExitActionPerformed
    System.exit(0);
    }//GEN-LAST:event_btn_MExitActionPerformed

    private void btn_MWHoursActionPerformed(java.awt.event.ActionEvent evt) {                                            
//GEN-FIRST:event_btn_MWHoursActionPerformed
    this.dispose(); 

    RF_View_Attendance workHours = new RF_View_Attendance(null, true, empID);
    workHours.setLocationRelativeTo(null);
    workHours.setVisible(true);
    }//GEN-LAST:event_btn_MWHoursActionPerformed

    private void btn_MPPayrollActionPerformed(java.awt.event.ActionEvent evt) {                                              
//GEN-FIRST:event_btn_MPPayrollActionPerformed
    this.dispose(); 
    
    RF_Generate makepayroll = new RF_Generate(null, true, empID);
    makepayroll.setLocationRelativeTo(null);
    
    makepayroll.setVisible(true);
    }//GEN-LAST:event_btn_MPPayrollActionPerformed

    private void btn_attendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attendanceActionPerformed
        this.dispose(); 
        RF_Attendance listWindow = new RF_Attendance(empID);
        listWindow.setLocationRelativeTo(null);
        listWindow.setVisible(true);
    }//GEN-LAST:event_btn_attendanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDialog_RF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDialog_RF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDialog_RF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDialog_RF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            MainDialog_RF dialog = new MainDialog_RF(new JFrame(), true, "0000", "First", "Last");
            dialog.setLocationRelativeTo(null);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    public void setLoggedInUser(String empID, String firstName, String lastName) {
    lbl_User.setText(lastName + ", " + firstName);
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MEDetails;
    private javax.swing.JButton btn_MExit;
    private javax.swing.JButton btn_MPPayroll;
    private javax.swing.JButton btn_MWHours;
    private javax.swing.JButton btn_attendance;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_User;
    private javax.swing.JLabel lbl_main;
    // End of variables declaration//GEN-END:variables


    private javax.swing.JTable payrollTable;
    private javax.swing.JScrollPane payrollScrollPane;
    private javax.swing.table.DefaultTableModel payrollTableModel;

} // 
