/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package motorphgui;

import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author admin
 */
public class MainDialog extends javax.swing.JDialog {

    /**
     * Creates new form MainDialog
     * @param parent
     * @param modal
     */
    public MainDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_MEDetails = new javax.swing.JButton();
        btn_MAttendance = new javax.swing.JButton();
        btn_MExit = new javax.swing.JButton();
        btn_MWHours = new javax.swing.JButton();
        btn_MPPayroll = new javax.swing.JButton();
        lbl_main = new javax.swing.JLabel();
        btn_MAddRem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MotorPH Payroll System");

        btn_MEDetails.setText("Employee Details");
        btn_MEDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MEDetailsActionPerformed(evt);
            }
        });

        btn_MAttendance.setText("Attendance");
        btn_MAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MAttendanceActionPerformed(evt);
            }
        });

        btn_MExit.setText("Exit");
        btn_MExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MExitActionPerformed(evt);
            }
        });

        btn_MWHours.setText("Work Hours");
        btn_MWHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MWHoursActionPerformed(evt);
            }
        });

        btn_MPPayroll.setText("Process Payroll");
        btn_MPPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MPPayrollActionPerformed(evt);
            }
        });

        lbl_main.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        lbl_main.setText("MotorPH Payroll System");

        btn_MAddRem.setText("Add/Remove Employee");
        btn_MAddRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MAddRemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btn_MEDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MWHours, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MPPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_MExit, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_main)
                    .addComponent(btn_MAddRem, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_main)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_MEDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_MAddRem, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_MAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_MWHours, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_MPPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_MExit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MEDetailsActionPerformed(java.awt.event.ActionEvent evt) {                                              
//GEN-FIRST:event_btn_MEDetailsActionPerformed
    Employee_Details empDetails = new Employee_Details(null, true);    
    empDetails.setVisible(true);    // TODO add your handling code here: 
    }//GEN-LAST:event_btn_MEDetailsActionPerformed

    private void btn_MAttendanceActionPerformed(java.awt.event.ActionEvent evt) {                                                
//GEN-FIRST:event_btn_MAttendanceActionPerformed
    View_Attendance attendance = new View_Attendance(null, true);
attendance.setVisible(true);
    }//GEN-LAST:event_btn_MAttendanceActionPerformed

    private void btn_MExitActionPerformed(java.awt.event.ActionEvent evt) {                                          
//GEN-FIRST:event_btn_MExitActionPerformed
    System.exit(0);
    }//GEN-LAST:event_btn_MExitActionPerformed

    private void btn_MWHoursActionPerformed(java.awt.event.ActionEvent evt) {                                            
//GEN-FIRST:event_btn_MWHoursActionPerformed
    View_Attendance workHours = new View_Attendance(null, true);
workHours.setVisible(true);
    }//GEN-LAST:event_btn_MWHoursActionPerformed

    private void btn_MPPayrollActionPerformed(java.awt.event.ActionEvent evt) {                                              
//GEN-FIRST:event_btn_MPPayrollActionPerformed
    ProcessPayroll payroll = new ProcessPayroll(); 
    payroll.setVisible(true); // Opens a new window showing payroll summary
    }//GEN-LAST:event_btn_MPPayrollActionPerformed

    private void btn_MAddRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MAddRemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_MAddRemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            MainDialog dialog = new MainDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_MAddRem;
    private javax.swing.JButton btn_MAttendance;
    private javax.swing.JButton btn_MEDetails;
    private javax.swing.JButton btn_MExit;
    private javax.swing.JButton btn_MPPayroll;
    private javax.swing.JButton btn_MWHours;
    private javax.swing.JLabel lbl_main;
    // End of variables declaration//GEN-END:variables

    // ✅ Custom fields (inside class)
    private javax.swing.JTable payrollTable;
    private javax.swing.JScrollPane payrollScrollPane;
    private javax.swing.table.DefaultTableModel payrollTableModel;

} // 
