/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package motorphgui;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author admin
 */
public class RF_Attendance extends javax.swing.JFrame {
    private String empID;

    
    public RF_Attendance(String empID) {
        this.empID = empID;
        initComponents();
        loadEmployeeData(empID, null); 

        combobox_cutoffperiod.addActionListener(e -> {
            String selectedPeriod = (String) combobox_cutoffperiod.getSelectedItem();
            if (!"Choose a Period".equals(selectedPeriod)) {
                loadEmployeeData(empID, selectedPeriod); // Pass as is, parse later
            } else {
                loadEmployeeData(empID, null);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_AttendanceView = new javax.swing.JTable();
        lbl_main = new javax.swing.JLabel();
        lbl_ED1 = new javax.swing.JLabel();
        combobox_cutoffperiod = new javax.swing.JComboBox<>();
        btn_Results_Home = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_AttendanceView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Last Name", "First Name", "SSS Number", "PhilHealth Number", "TIN", "Pag-IBIG Number"
            }
        ));
        jScrollPane1.setViewportView(table_AttendanceView);

        lbl_main.setBackground(new java.awt.Color(204, 255, 255));
        lbl_main.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        lbl_main.setText("Attendance Viewer");
        lbl_main.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_ED1.setText("Cut-off Period:");

        combobox_cutoffperiod.setForeground(new java.awt.Color(153, 153, 153));
        combobox_cutoffperiod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Period", "June 15 2024", "June 30 2024", "July 15 2024", "July 31 2024", "August 15 2024", "August 31 2024", "September 15 2024", "September 30 2024", "October 15 2024", "October 31 2024", "November 15 2024", "November 30 2024", "December 15 2024", "December 31 2024" }));

        btn_Results_Home.setText("Back to Main");
        btn_Results_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Results_HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(lbl_ED1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combobox_cutoffperiod, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_main)
                        .addGap(336, 336, 336))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_Results_Home)
                        .addGap(361, 361, 361))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_main)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ED1)
                    .addComponent(combobox_cutoffperiod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Results_Home)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Results_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Results_HomeActionPerformed
        this.dispose();

        String empID = "";
        String lastName = "";
        String firstName = "";

        DefaultTableModel model = (DefaultTableModel) table_AttendanceView.getModel();

        if (model.getRowCount() > 0) {
            empID = model.getValueAt(0, 0).toString();    
            lastName = model.getValueAt(0, 1).toString(); 
            firstName = model.getValueAt(0, 2).toString(); 
        }

        MainDialog_RF MainDia = new MainDialog_RF(this, true, empID, firstName, lastName);
        MainDia.setLocationRelativeTo(null);
        MainDia.setVisible(true);
    }//GEN-LAST:event_btn_Results_HomeActionPerformed

    /**
     * @param args the command line arguments
     */

    private void loadEmployeeData(String empID, String cutoffPeriod) {
        String[] columnNames = {"Employee ID", "Last Name", "First Name", "Date", "Log In", "Log Out"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        try {
            String filePath = getClass().getResource("/attendance_data.csv").getPath();
            List<String[]> rows = CSVUtil.readCSV(filePath);

            DateTimeFormatter csvFormatter = DateTimeFormatter.ofPattern("MM/dd/yyyy");
            LocalDate periodStart = null;
            LocalDate periodEnd = null;

            if (cutoffPeriod != null && !"Choose a Period".equals(cutoffPeriod)) {
                DateTimeFormatter inputFormatter = DateTimeFormatter.ofPattern("MMMM d yyyy");
                periodEnd = LocalDate.parse(cutoffPeriod, inputFormatter);

                // Determine start date (previous cutoff + 1)
                int selectedIndex = combobox_cutoffperiod.getSelectedIndex();

                if (selectedIndex > 1) {
                    // Previous cutoff exists
                    String prevCutoff = combobox_cutoffperiod.getItemAt(selectedIndex - 1);
                    LocalDate prevDate = LocalDate.parse(prevCutoff, inputFormatter);
                    periodStart = prevDate.plusDays(1);
                } else {
                    // First cutoff in the list, start from earliest possible
                    periodStart = periodEnd.minusDays(14);
                }
            }

            if (rows != null && !rows.isEmpty()) {
                for (int i = 1; i < rows.size(); i++) {
                    String[] data = rows.get(i);
                    if (data.length >= 6) {
                        String rowEmpID = data[0].trim();
                        LocalDate date = LocalDate.parse(data[3].trim(), csvFormatter);

                        boolean withinPeriod = true;

                        if (periodStart != null && periodEnd != null) {
                            withinPeriod = (!date.isBefore(periodStart)) && (!date.isAfter(periodEnd));
                        }

                        if (rowEmpID.equals(empID) && withinPeriod) {
                            String[] row = {
                                data[0].trim(),
                                data[1].trim(),
                                data[2].trim(),
                                data[3].trim(),
                                data[4].trim(),
                                data[5].trim()
                            };
                            model.addRow(row);
                        }
                    }
                }
            }

            table_AttendanceView.setModel(model);
            table_AttendanceView.setDefaultEditor(Object.class, null);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading employee data: " + e.getMessage());
        }
    }

    
    
        public static void main(String args[]) {
            try {
                for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (Exception ex) {
                java.util.logging.Logger.getLogger(RF_Attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

            java.awt.EventQueue.invokeLater(() -> {
                RF_Attendance frame = new RF_Attendance("10001");
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            });
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Results_Home;
    private javax.swing.JComboBox<String> combobox_cutoffperiod;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ED1;
    private javax.swing.JLabel lbl_main;
    private javax.swing.JTable table_AttendanceView;
    // End of variables declaration//GEN-END:variables
}
