/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package motorphgui;

import javax.swing.*;
import java.util.List;



/**
 *
 * @author admin
 */
public class RF_Employee_DetailsResult extends javax.swing.JDialog {


    public RF_Employee_DetailsResult(java.awt.Frame parent, boolean modal, String empID) {
        super(parent, modal);
        initComponents();

        List<String[]> allEmployees = CSVUtil.readCSV("src/main/resources/employee-data.csv");
        
        String[] data = null;
        
        if (allEmployees != null) {
        for (String[] row : allEmployees) {
            if (row.length > 0 && row[0].equals(empID)) { 
                data = row;
                break;
            }
        }
    }
        
        
        if (data != null && data.length >= 19) {
            lbl_resID.setText(data[0]);
            lbl_resName.setText(data[1] + ", " + data[2]);
            lbl_resBday.setText(data[3]);
            lbl_resAdd.setText("<html>" + data[4] + "</html>");
            lbl_resPhone.setText(data[5]);
            lbl_resSSS.setText(data[6]);
            lbl_resPIN.setText(data[7]);
            lbl_resTIN.setText(data[8]);
            lbl_resMID.setText(data[9]);
            lbl_resES.setText(data[10]);
            lbl_resPOS.setText(data[11]);
            lbl_resIS.setText(data[12]);
            
            
            lbl_resBasicSal.setText(formatCurrency(data[13]));
            lbl_resRiceSub.setText(formatCurrency(data[14]));
            lbl_resPhoneAllowance.setText(formatCurrency(data[15]));
            lbl_resClothing.setText(formatCurrency(data[16]));
            lbl_resSemiMonthly.setText(formatCurrency(data[17]));
            lbl_resHourly.setText(formatCurrency(data[18]));

            double rice = parseAmount(data[14]);
            double phone = parseAmount(data[15]);
            double clothing = parseAmount(data[16]);
            double proratedTotal = rice + phone + clothing;
            lbl_resProratedAll.setText(formatCurrency(String.valueOf(proratedTotal)));

        } else {
            JOptionPane.showMessageDialog(this, "⚠️ Invalid employee data received.");
        }
    }

    private double parseAmount(String raw) {
    try {
        return Double.parseDouble(raw);
    } catch (NumberFormatException e) {
        return 0.0;
    }
}
    
    private String formatCurrency(String raw) {
        try {
            double value = Double.parseDouble(raw);
            return String.format("₱%,.2f", value);
        } catch (NumberFormatException e) {
            return raw;
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_main = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbl_resID = new javax.swing.JLabel();
        lbl_resName = new javax.swing.JLabel();
        lbl_resBday = new javax.swing.JLabel();
        lbl_resAdd = new javax.swing.JLabel();
        lbl_resPhone = new javax.swing.JLabel();
        lbl_resSSS = new javax.swing.JLabel();
        lbl_resPIN = new javax.swing.JLabel();
        lbl_resTIN = new javax.swing.JLabel();
        lbl_resMID = new javax.swing.JLabel();
        lbl_resES = new javax.swing.JLabel();
        lbl_resPOS = new javax.swing.JLabel();
        lbl_resIS = new javax.swing.JLabel();
        lbl_resBasicSal = new javax.swing.JLabel();
        lbl_resRiceSub = new javax.swing.JLabel();
        lbl_resPhoneAllowance = new javax.swing.JLabel();
        lbl_resClothing = new javax.swing.JLabel();
        lbl_resSemiMonthly = new javax.swing.JLabel();
        lbl_resHourly = new javax.swing.JLabel();
        lbl_resProratedAll = new javax.swing.JLabel();
        btn_Results_Home = new javax.swing.JButton();
        btn_Results_Home1 = new javax.swing.JButton();
        btn_Results_UpdateRec = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_main.setBackground(new java.awt.Color(204, 255, 255));
        lbl_main.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        lbl_main.setText("Employee Details");

        jLabel1.setText("Employee ID:");

        jLabel2.setText("Name:");

        jLabel3.setText("Birthday:");

        jLabel4.setText("Address:");

        jLabel5.setText("SSN:");

        jLabel6.setText("Phone Number:");

        jLabel7.setText("PhilHealth Number:");

        jLabel8.setText("TIN:");

        jLabel9.setText("Pag-Ibig Number:");

        jLabel10.setText("Employment Status:");

        jLabel11.setText("Position:");

        jLabel12.setText("Immediate Supervisor:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Basic Salary:");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel14.setText("Rice Subsidy:");

        jLabel15.setText("Phone Allowance:");

        jLabel16.setText("Clothing Allowance:");

        jLabel17.setText("Gross Semi-Monthly Rate:");

        jLabel18.setText("Hourly Rate:");

        jLabel19.setText("Pro-rated Total Allowance:");

        lbl_resID.setText("EMP_ID_RESULT");

        lbl_resName.setText("EMP_NAME_RESULT");

        lbl_resBday.setText("EMP_BDAY_RESULT");

        lbl_resAdd.setText("EMP_ADDRESS_RESULT");
        lbl_resAdd.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbl_resPhone.setText("EMP_PHONE_RESULT");

        lbl_resSSS.setText("EMP_SSS_RESULT");

        lbl_resPIN.setText("EMP_PIN_RESULT");

        lbl_resTIN.setText("EMP_TIN_RESULT");

        lbl_resMID.setText("EMP_MID_RESULT");

        lbl_resES.setText("EMP_ES_RESULT");

        lbl_resPOS.setText("EMP_POS_RESULT");

        lbl_resIS.setText("EMP_IS_RESULT");

        lbl_resBasicSal.setText("EMP_Basic_RESULT");

        lbl_resRiceSub.setText("EMP_RiceSub_RESULT");

        lbl_resPhoneAllowance.setText("EMP_PhoneAllowance_RESULT");

        lbl_resClothing.setText("EMP_Clothing_RESULT");

        lbl_resSemiMonthly.setText("EMP_GSMR_RESULT");

        lbl_resHourly.setText("EMP_HRate_RESULT");

        lbl_resProratedAll.setText("EMP_PTA_RESULT");

        btn_Results_Home.setText("Back to Main");
        btn_Results_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Results_HomeActionPerformed(evt);
            }
        });

        btn_Results_Home1.setText("Exit");
        btn_Results_Home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Results_Home1ActionPerformed(evt);
            }
        });

        btn_Results_UpdateRec.setForeground(new java.awt.Color(51, 102, 0));
        btn_Results_UpdateRec.setText("Update Record");
        btn_Results_UpdateRec.setToolTipText("");
        btn_Results_UpdateRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Results_UpdateRecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(lbl_main))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(lbl_resID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(lbl_resBasicSal))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(lbl_resName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(lbl_resRiceSub, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(lbl_resBday, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(lbl_resPhoneAllowance, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(lbl_resAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_resClothing, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_resSemiMonthly, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lbl_resPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(lbl_resHourly, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(lbl_resSSS, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lbl_resProratedAll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_resPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(lbl_resTIN, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lbl_resMID, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lbl_resES, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lbl_resPOS, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lbl_resIS, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(btn_Results_Home)
                .addGap(31, 31, 31)
                .addComponent(btn_Results_UpdateRec)
                .addGap(43, 43, 43)
                .addComponent(btn_Results_Home1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbl_main)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lbl_resID)
                    .addComponent(jLabel13)
                    .addComponent(lbl_resBasicSal))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lbl_resName)
                    .addComponent(jLabel14)
                    .addComponent(lbl_resRiceSub))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lbl_resBday)
                    .addComponent(jLabel15)
                    .addComponent(lbl_resPhoneAllowance))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lbl_resAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_resClothing)
                        .addGap(6, 6, 6)
                        .addComponent(lbl_resSemiMonthly)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lbl_resPhone)
                    .addComponent(jLabel18)
                    .addComponent(lbl_resHourly))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lbl_resSSS)
                    .addComponent(jLabel19)
                    .addComponent(lbl_resProratedAll))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lbl_resPIN))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lbl_resTIN))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lbl_resMID))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lbl_resES))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lbl_resPOS))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(lbl_resIS))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Results_Home)
                    .addComponent(btn_Results_UpdateRec)
                    .addComponent(btn_Results_Home1))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Results_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Results_HomeActionPerformed
        this.dispose();

        String empID = lbl_resID.getText();
        String[] nameParts = lbl_resName.getText().split(",", 2);
        String lastName = nameParts.length > 0 ? nameParts[0].trim() : "";
        String firstName = nameParts.length > 1 ? nameParts[1].trim() : "";

        MainDialog_RF MainDia = new MainDialog_RF(null, true, empID, firstName, lastName);
        MainDia.setVisible(true);
    }//GEN-LAST:event_btn_Results_HomeActionPerformed

    private void btn_Results_Home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Results_Home1ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Results_Home1ActionPerformed

    private void btn_Results_UpdateRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Results_UpdateRecActionPerformed
        this.dispose();
        RF_Employee_DetailsUpdate updateDialog = new RF_Employee_DetailsUpdate(null, true, lbl_resID.getText());
        updateDialog.setVisible(true);
    }//GEN-LAST:event_btn_Results_UpdateRecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            
            String dummyEmpID = "10001"; 

            RF_Employee_DetailsResult dialog = new RF_Employee_DetailsResult(
                new JFrame(),
                true,
                dummyEmpID 
            );

            dialog.setLocationRelativeTo(null); 
            dialog.setVisible(true);
        });


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Results_Home;
    private javax.swing.JButton btn_Results_Home1;
    private javax.swing.JButton btn_Results_UpdateRec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_main;
    private javax.swing.JLabel lbl_resAdd;
    private javax.swing.JLabel lbl_resBasicSal;
    private javax.swing.JLabel lbl_resBday;
    private javax.swing.JLabel lbl_resClothing;
    private javax.swing.JLabel lbl_resES;
    private javax.swing.JLabel lbl_resHourly;
    private javax.swing.JLabel lbl_resID;
    private javax.swing.JLabel lbl_resIS;
    private javax.swing.JLabel lbl_resMID;
    private javax.swing.JLabel lbl_resName;
    private javax.swing.JLabel lbl_resPIN;
    private javax.swing.JLabel lbl_resPOS;
    private javax.swing.JLabel lbl_resPhone;
    private javax.swing.JLabel lbl_resPhoneAllowance;
    private javax.swing.JLabel lbl_resProratedAll;
    private javax.swing.JLabel lbl_resRiceSub;
    private javax.swing.JLabel lbl_resSSS;
    private javax.swing.JLabel lbl_resSemiMonthly;
    private javax.swing.JLabel lbl_resTIN;
    // End of variables declaration//GEN-END:variables
}
