/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package motorphgui;

import java.util.List;
import javax.swing.*;

/**
 *
 * @author admin
 */

public class RF_View_Attendance extends javax.swing.JDialog {
    
    private final String empID;


    /**
     * Creates new form Employee_Details
     */
    public RF_View_Attendance(java.awt.Frame parent, boolean modal, String empID) {
        super(parent, modal);
        this.empID = empID; 
        initComponents();

         
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_main = new javax.swing.JLabel();
        lbl_ED = new javax.swing.JLabel();
        btn_View = new javax.swing.JButton();
        lbl_ED1 = new javax.swing.JLabel();
        combobox_cutoffperiod = new javax.swing.JComboBox<>();
        lbl_EmpID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_main.setFont(new java.awt.Font("Sans Serif Collection", 1, 18)); // NOI18N
        lbl_main.setText("Attendance");

        lbl_ED.setText("Employee ID:");

        btn_View.setText("View");
        btn_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ViewActionPerformed(evt);
            }
        });

        lbl_ED1.setText("Cut-off Period");

        combobox_cutoffperiod.setForeground(new java.awt.Color(153, 153, 153));
        combobox_cutoffperiod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a Period", "June 15 2024", "June 30 2024", "July 15 2024", "July 31 2024", "August 15 2024", "August 31 2024", "September 15 2024", "September 30 2024", "October 15 2024", "October 31 2024", "November 15 2024", "November 30 2024", "December 15 2024", "December 31 2024" }));

        lbl_EmpID.setText("jLabel19");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbl_ED1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(lbl_ED, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combobox_cutoffperiod, 0, 169, Short.MAX_VALUE)
                    .addComponent(lbl_EmpID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btn_View)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_main)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_main)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ED)
                    .addComponent(lbl_EmpID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_ED1)
                    .addComponent(combobox_cutoffperiod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_View)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ViewActionPerformed
        this.dispose();   
        String selectedPeriod = (String) combobox_cutoffperiod.getSelectedItem();

        if (selectedPeriod == null || selectedPeriod.equals("Choose a Period")) {
            JOptionPane.showMessageDialog(this, "Please select a Cut-off Period.");
            return;
        }

        RF_WHours workHoursDialog = new RF_WHours(
        new javax.swing.JFrame(), true, empID, selectedPeriod);
        
        workHoursDialog.setLocationRelativeTo(null);
        workHoursDialog.setVisible(true);
    }//GEN-LAST:event_btn_ViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            RF_View_Attendance dialog = new RF_View_Attendance(new javax.swing.JFrame(), true, "10001");
            dialog.setLocationRelativeTo(null);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_View;
    private javax.swing.JComboBox<String> combobox_cutoffperiod;
    private javax.swing.JLabel lbl_ED;
    private javax.swing.JLabel lbl_ED1;
    private javax.swing.JLabel lbl_EmpID;
    private javax.swing.JLabel lbl_main;
    // End of variables declaration//GEN-END:variables
}
